### PR TITLE
feat: add support for react

### LINKED ISSUE #33: [Feature Request] Add React (JSX) support
Currently, there is no autocomplete in JSX `className` props for CSS classes. Please add a support for React and JSX/TSX as well.

### PR DESCRIPTION
**Pull request by ultrox**
Thanks for making this nice extensions I like using it in .html files and wanted to see  would you considering adding my changes to support react?

Didn't want to touch too much stuff, but my prettier took over so I committed that as well.

Here is all the languages supported now.

BTW: npm complained about v1 for package lock, so that was auto updated.

### Vue
Screenshot 2023-04-22 at 19 10 47

### React javascript
Screenshot 2023-04-22 at 19 10 32

### React typescript
Screenshot 2023-04-22 at 19 10 17

### HTML
Screenshot 2023-04-22 at 19 10 04

### CODE REVIEW

**Comment by andersea** [comment]
Hi! Thank you very much for this work. I will review it asap.

**Comment by andersea** [comment]
@ultrox Can you test this version?
[html-class-suggestions-1.2.0.zip](https://github.com/andersea/HTMLClassSuggestionsVSCode/files/11303839/html-class-suggestions-1.2.0.zip)

**Comment by ultrox** [comment]
Let me try it out.

**Comment by ultrox** [comment]
Works as expected for all supported types.

**Comment by andersea** [comment]
Fantastic! Thanks again! I'll upload this version later today!

**Pull request merged**
